name: 'GIFS_coco20i_1shot_base'
BASE_YAML: '../coco20i_base.yaml'

# GIFS
TASK_SPECIFIC:
  GIFS:
    max_iter: 100
    num_shots: 1

# PIFS
# TASK_SPECIFIC:
#   GIFS:
#     fine_tuning: True
#     pseudo_base_label: False
#     max_iter: 100
#     num_shots: 1
#     ft_batch_size: 10
#     backbone_lr: 1e-4
#     classifier_lr: 1e-3
#     feature_reg_lambda: 0.0
#     classifier_reg_lambda: 20.0
#     context_aware_sampling_prob: 0.0
#     sequential_dataset_num_classes: 5
#     baseset_type: 'random'
#     num_runs: 5
